### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ACollectionOfAtoms** [cjsaylor/atom-irc#13]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
IrcStatusView.module.exports.IrcStatusView.attach (/Users/Adam/.atom/packages/irc/lib/irc-status-view.coffee:23:21)
```

**Comment by cjsaylor** [comment]
@ACollectionOfAtoms Thanks for the heads up!

**Comment by cjsaylor** [comment]
Fixed.
